name: SellAll
main: AndreasHGK\SellAll\SellAll
version: 1.3.0
api: 3.0.0
load: POSTWORLD
author: AndreasHGK
description: Sell all items in your hand or all items in your inventory with the same type as in your hand
depend: ["EconomyAPI"]

commands:
 sell:
  description: "§d§lSell commands §r§bi|inv|all|hand|ores "
  usage: "/sell all|hand|i"
  permission: sellall.command

permissions:
 sellall:
  default: op
  description: "SellALl root permission"
  children:
   sellall.command:
    default: true
    description: "Allows the use of /sell"
   sellall.reload:
    default: op
    description: "Reloads the plugin"
