name: SellAll
main: AndreasHGK\SellAll\SellAll
version: 1.1.1
api: 3.0.0
load: POSTWORLD
author: AndreasHGK
description: Sell all items in your hand or all items in your inventory with the same type as in your hand
depend: ["EconomyAPI"]

commands:
 sell:
  description: "Sell command"
  usage: "/sell all|hand|inventory"
  permission: sellall.command

permissions:
 sellall:
  default: true
  description: "SellALl root permission"
  children:
   sellall.command:
    default: true
    description: "Allows the use of /sell"